### ISSUE TITLE
Implement Default for Conf

### ISSUE THREAD

**Issue by lu-zero** [rust-italia/mdev-parser#8]
`mdev.c` assumes the final rule is a catch-all default that creates the device according to the information provided by the kernel.
Would be good to make so Conf::default() fits the correct behavior.

**Comment by lu-zero** [comment]
It is needed to implement https://github.com/rust-italia/mdev/issues/15

**Comment by mdnmdn** [comment]
For the cach-all default rule:

- filter should be a regex as `.*` ?
- user & group empy string?

**Comment by lu-zero** [comment]
user & group should be `root`

**Comment by lu-zero** [comment]
Addressed in #9
